export interface Requirement{
    id:string,
    employeeId: string,
    polygraph: string,
  phyExam: string,
  sssNo: string,
  residentCert: string,
  tor: string,
  drvLicense: string,
  empCert: string,
  itr: string,
  tinNo: string,
  philhealthNo: string,
  pagibigNo: string,
  nbi: string,
  marriageCert: string,
  pic: string,
  clearance: string,
  isPolygraph: true,
  isPhyExam: true,
  isSSSNo: true,
  isResidentCert: true,
  isTOR: true,
  isDrvLicense: true,
  isEmpCert: true,
  isITR: true,
  isTinNo: true,
  isPhilhealthNo: true,
  isPic: true,
  isPagibig: true,
  isNbi: true,
  isMarriageCert: true,
  isClearance: true
}